### PR TITLE
Fixed profile page completely

### LINKED ISSUE #19: Dashboard add new pantry functionality

### LINKED ISSUE #20: Dashboard add Existing pantry functionality

### PR DESCRIPTION
**Pull request by jerrylee17**
Resolves #19 
Resolves #20

### CODE REVIEW

File: src/Pages/Dashboard/AddPantryTab.js [hunk 1]
```diff
@@ -0,0 +1,135 @@
...
+  },
+  section: {
+    flexGrow: 1,
+    width: '50%',
+    minHeight: '90%',
+    // '&:hover': {
+    //   transform: 'scale(1.02)',
+    //   transitionDuration: '500ms',
+    //   transitionProperty: 'transform',
+    // }
```
Comment (hsorathia) [inline src/Pages/Dashboard/AddPantryTab.js:27]: y o

**Review by hsorathia — APPROVED** [review]
